title: Test Map
description: This website demonstrates how to easily publish and display an interactive map made with Folium. It features some Natural monuments near the Oder River.
theme: Minimal
Logo: https://upload.wikimedia.org/wikipedia/commons/thumb/4/49/Naturdenkmal-Schild_2014-06_Berlin-Wartb_1483-1363-120.jpg/1200px-Naturdenkmal-Schild_2014-06_Berlin-Wartb_1483-1363-120.jpg
